# frozen_string_literal: true
OBJECTS = %w(
  arp.o
  dhcp.o
  forward.o
  icmp.o
  ipv4.o
  route.o
  socket.o
  tcp.o
  udp.o
).freeze

EXTRA_LIBS = '-lgcc'.freeze
LIBRARIES = %w(
  ipc
  ipv4
  list
  log
  memory
  random
  string
  system
  time
).freeze

OUTPUT = 'ipv4'.freeze

load '../../servers.rake'
