OBJECTS = %w(
  arp.o
  dhcp.o
  forward.o
  icmp.o
  ipv4.o
  route.o
  socket.o
  tcp.o
  udp.o
)

LIBRARIES = %w(
  ipc
  ipv4
  log
  memory
  random
  time
  string
  system
)

OUTPUT = 'ipv4'

load '../../servers.rake'
