Metrics/LineLength:
  Max: 132
Style/AndOr:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ElseAlignment:
  Enabled: false
Lint/EndAlignment:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
Style/IndentationWidth:
  Enabled: false
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
