inherit_from: .rubocop_todo.yml

Layout/ElseAlignment:
  Enabled: false
Layout/EmptyLinesAroundArguments:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Lint/EndAlignment:
  Enabled: false
Metrics/LineLength:
  Max: 132
Style/AndOr:
  Enabled: false
Style/AsciiComments:
  Enabled: false

# Gives false positives on inline assembly (%eax, %ebx etc)
Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
# Style/GuardClause:
#   Enabled: false

Style/NegatedIf:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false
