# frozen_string_literal: true
OBJECTS = %w(
  clusters.o
  detect_fat.o
  fat.o
  fat_directory_read.o
  fat_directory_entry_read.o
  fat_file_get_info.o
  fat_file_open.o
  fat_file_read.o
  get_entry_by_name.o
  handle_connection.o
  read_long_file_name.o
).freeze

LIBRARIES = %w(
  ipc
  log
  memory
  string
  system
).freeze

OUTPUT = 'fat'.freeze
EXTRA_LDFLAGS_PRE = '-Wl,--defsym=PROCESS_VM_BASE=0x48000000'.freeze

load '../../servers.rake'
