# frozen_string_literal: true

OBJECTS = %w[
  circular_queue_test.o
  generic_tests_main.o
].freeze

OUTPUT = :generic_tests

# CFLAGS are set in storm_tests.rake

# All functions overridden by tests must explicitly be listed here, to let the linker redirect
# the function calls to the wrappers instead of the real implementations.
#
# Like this: -Wl,--wrap=memory_global_allocate
LDFLAGS = %w[
  -m32
  -L/usr/local/lib
  -L../../storm/generic
  -L../../storm/x86
].freeze

# Yes, the storm_* actually need to be specified this many times.
# Without it, GNU ld fails to figure out how to link the tests together.
LIBRARIES = %w[
  cmocka

  storm_x86
  storm_generic
  storm_x86
  storm_generic
  storm_x86
].freeze

task default: [:banner, OUTPUT]

task :banner do
  print 'Compiling '.bold
  print 'storm_tests/generic'.cyan.bold
  puts '...'

  print '    '
end

file OUTPUT => OBJECTS + ['../../storm/generic/libstorm_generic.a', '../../storm/x86/libstorm_x86.a'] do |t|
  begin
    puts
    puts
    puts '    Linking...'.blue.bold

    inputs = OBJECTS.join(' ')
    command = " \
      #{CC} -o #{t.name} #{inputs} \
      #{LDFLAGS.join(' ')} -l#{LIBRARIES.join(' -l')}"
    sh command
  rescue StandardError
    puts "Error linking kernel. Full command line was: #{command}"
    raise
  end
end

task :test do
  puts
  run_test OUTPUT
end

# TODO: Check if we can get Rake's automatic 'clean' support working, so we don't have to do this manually.
task :clean do
  rm_f OBJECTS
  rm_f OUTPUT.to_s
end

load '../storm_tests.rake'
