/* Automatically generated by autochaos 0.2.1. Not intended to be
   hand edited. */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define PACKAGE_NAME "serial"
#define PACKAGE_VERSION "0.0.5"


#endif /* !__CONFIG_H__ */