# frozen_string_literal: true
OBJECTS = %w(
  virtual_file_system.o
).freeze

LIBRARIES = %w(
  ipc
  memory
  log
  string
  system
).freeze

OUTPUT = 'virtual_file_system'.freeze

load '../../servers.rake'
