Rake.application.options.rakelib = pwd + "/../rakelib" if Rake.application.options.rakelib.first == 'rakelib'

libraries = %w(
  string
  system
  ipc
)

# These haven't been upgraded to work w/ Rake yet.
#  execute_elf
#  memory
#  unicode
#  ipv4
#  video
#  serial
#  console
#  random
#  log
#  file
#  math
#  checksum
#  mutex
#  pci
#  time
#  list
#  sound

load 'constants.rake'

INCLUDES = %w(
  -I.
  -I../storm/include
)

task :default => libraries + [ :startup ] do |t|
  libraries.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND}"
  end
end

task :startup => [ :banner, 'startup.o' ] do
  puts
end

task :banner do
  print 'Compiling '.bold
  print 'startup.o'.cyan.bold
  puts '...'

  print '    '
end

task :clean do
  libraries.each do |folder|
    sh "cd #{folder} && rake -N clean"
  end

  rm_f 'startup.o'
end

task :install => :default do
  libraries.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} install"
  end
end
