Rake.application.options.rakelib = [pwd + '/../rakelib'] if Rake.application.options.rakelib.first == 'rakelib'

libraries = %w(
  console
  execute_elf
  file
  ipc
  ipv4
  list
  log
  memory
  pci
  random
  string
  system
  time
  unicode
  video
)

# These haven't been upgraded to work w/ Rake yet.
#  serial
#  math
#  checksum
#  mutex
#  sound

load 'constants.rake'

INCLUDES = %w(
  -I.
  -I../storm/include
)

task :default => libraries + [ :startup ] do |t|
  libraries.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND}"
  end
end

task :startup => [ :banner, 'startup.o' ] do
  puts
  puts # TODO: Should only get run sometimes...
end

task :banner do
  print 'Compiling '.bold
  print 'startup.o'.cyan.bold
  puts '...'

  print '    '
end

task :clean do
  libraries.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} clean"
  end

  rm_f 'startup.o'
  rm_f Dir['*.a']
end

task :install => :default do
  libraries.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} install"
  end
end
