OBJECTS = %w(
  arguments.o
  avl.o
  avl_debug.o
  avl_rotate.o
  avl_update.o
  avl_delete.o
  debug.o
  idle.o
  init.o
  kernelfs.o
  log.o
  mailbox.o
  memory.o
  service.o
  slab.o
  system_call.o
  tag.o
  time.o
)

# TODO: Would like to use STORM_GENERIC_LIB, but for whatever reason it is not available in this context.
OUTPUT = 'libstorm_generic.a'

task :default => [ :banner, OUTPUT ] do
  puts
end

task :banner do
  print "Compiling ".bold
  print "storm/generic".cyan.bold
  puts "..."

  print "    "
end

load '../storm.rake'
