Rake.application.options.rakelib = [pwd + '/../../rakelib'] if Rake.application.options.rakelib.first == 'rakelib'

subfolders = %w(
  boot
  console
  keyboard
  log
)

# Not yet converted to Rake:
#
# pci

task :default => subfolders do |t|
  t.prerequisites.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND}"
  end
end

task :clean do
  subfolders.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} clean"
  end
end

task :install => :default do
  subfolders.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} install"
  end
end
