# frozen_string_literal: true

Rake.application.options.rakelib = [pwd + '/../rakelib'] if Rake.application.options.rakelib.first == 'rakelib'

subfolders = %w[
  generic
  x86
]

task default: subfolders do |t|
  t.prerequisites.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND}"
  end
end

task :clean do
  subfolders.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} clean"
  end
end

task build_tests: :default do
  subfolders.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} build_tests"
  end
end

task :test do
  subfolders.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} test"
  end
end

# No-op, just to not interfere with top-level Rakefile
task :install
