# frozen_string_literal: true
Rake.application.options.rakelib = [pwd + '/../rakelib'] if Rake.application.options.rakelib.first == 'rakelib'

subfolders = %w(
  block
  file_system
  network
  system
  video
)

# These haven't been upgraded to work w/ Rake yet.
# system
# sound
# other

task default: subfolders do |t|
  t.prerequisites.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND}"
  end
end

task :clean do
  subfolders.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} clean"
  end
end

task install: :default do
  subfolders.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} install"
  end
end
