Rake.application.options.rakelib = pwd + "/../rakelib" if Rake.application.options.rakelib.first == 'rakelib'

subfolders = %w(
  video
)

# These haven't been upgraded to work w/ Rake yet.
# network
# system
# file_system
# sound
# other
# block

task :default => subfolders do |t|
  t.prerequisites.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND}"
  end
end

task :clean do
  subfolders.each do |folder|
    sh "cd #{folder} && rake -N clean"
  end
end

task :install => :default do
  subfolders.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} install"
  end
end
