DEFINES = (ENV['DEFINES'] || '') + " -DPACKAGE=\\\"storm\\\" -DVERSION=\\\"git\\\" -DCREATOR=\\\"`whoami`@`hostname`\\\""

CFLAGS = 
"-Wall -W -Wshadow -Wpointer-arith -Waggregate-return -Wstrict-prototypes \
-Wredundant-decls -Winline -Wmissing-prototypes -Werror -Wcast-align \
-Wbad-function-cast -Wsign-compare -Wmissing-declarations \
-Wmissing-noreturn -pipe -Wnested-externs -O3 -fno-builtin -funsigned-char \
-g -m32 -fomit-frame-pointer -ffreestanding #{ENV['EXTRA_CFLAGS']} #{DEFINES}"

INCLUDES =
"-I../include \
-I.. \
-I."

OBJECTS = %w(
  cluster.o
  cpuid.o
  debug.o
  dispatch.o
  dma.o
  elf.o
  gdt.o
  idt.o
  init.o
  irq.o
  irq_handlers.o
  limits.o
  main.o
  memory.o
  memory_global.o
  memory_physical.o
  memory_virtual.o
  multiboot.o
  mutex.o
  port.o
  process.o
  schedule.o
  string.o
  system_calls-auto.o
  system_calls.o
  thread.o
  time.o
  timer.o
  trap.o
  wrapper.o
)

task :default => [ :banner ] + OBJECTS do
  puts
end

task :banner do
  print "Compiling ".bold
  print "storm/ia32".cyan.bold
  puts "..."

  print "    "
end

# TODO: Check if we can get Rake's automatic 'clean' support working, so we don't have to do this manually.
task :clean do
  rm_f OBJECTS
end
