/* Automatically generated by autochaos 0.2.1. Not intended to be
   hand edited. */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define PACKAGE_NAME "storm"
#define PACKAGE_VERSION "0.5.1"

#define OPTION_RELEASE FALSE

#endif /* !__CONFIG_H__ */
