Rake.application.options.rakelib = [pwd + '/../rakelib'] if Rake.application.options.rakelib.first == 'rakelib'

task :default => [ 'current-arch', 'include/storm/current-arch' ] do
  [ 'generic', 'current-arch' ].each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND}"
  end
end

task :clean do
  # Cannot use current-arch here, since it may not exist any more (if you run 'rake clean' multiple times).
  [ 'generic', TARGET_ARCH ].each do |folder|
    sh "cd #{folder} && rake clean"
  end

  rm_f [ 'current-arch', 'include/storm/' + TARGET_ARCH ]
end

task :install => :default do
  sh "cd #{TARGET_ARCH} && #{RAKE_COMMAND} install"
end

file 'current-arch' do
  ln_sf TARGET_ARCH, 'current-arch'
end

file 'include/storm/current-arch' do
  # The first argument here is actually non-qualified, which is the way it seems like it should be oddly enough...
  ln_sf TARGET_ARCH, 'include/storm/current-arch'
end
