# frozen_string_literal: true

OBJECTS = %w[
  common.o
  controller.o
  init.o
  keyboard.o
  mouse.o
].freeze

LIBRARIES = %w[
  console
  ipc
  log
  memory
  string
  system
].freeze

OUTPUT = 'keyboard'.freeze

load '../../servers.rake'
