/* Automatically generated by autochaos 0.2.0. Not intended to be
   hand edited. */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define PACKAGE_NAME "3c509"
#define PACKAGE_VERSION "0.0.1"

#include <ipc/ipc.h>
#include <log/log.h>
#include <string/string.h>
#include <system/system.h>
#include <memory/memory.h>
#include <network/network.h>

#endif /* !__CONFIG_H__ */