/* Automatically generated by autochaos 0.2.1. Not intended to be
   hand edited. */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define PACKAGE_NAME "console"
#define PACKAGE_VERSION "0.0.2"

#include <ipc/ipc.h>
#include <string/string.h>
#include <system/system.h>
#include <video/video.h>
#include <unicode/unicode.h>
#include <memory/memory.h>

#endif /* !__CONFIG_H__ */