# frozen_string_literal: true

OBJECTS = %w[
  connection.o
  console.o
  console_output.o
  console_output_all.o
].freeze

LIBRARIES = %w[
  ipc
  memory
  string
  system
  unicode
  video
].freeze

OUTPUT = 'console'.freeze

load '../../servers.rake'
