/* Automatically generated by autochaos 0.1.0. Not intended to be
   hand edited. */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define PACKAGE_NAME "iso"
#define PACKAGE_VERSION "0.0.1"


#endif /* !__CONFIG_H__ */