/* Automatically generated by autochaos 0.2.0. Not intended to be
   hand edited. */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define PACKAGE_NAME "stormG2"
#define PACKAGE_VERSION "0.0.1"

#define OPTION_NETBSD FALSE
#define OPTION_RELEASE FALSE
#define OPTION_FREEBSD FALSE
#define OPTION_OPENBSD FALSE

#endif /* !__CONFIG_H__ */