# frozen_string_literal: true

OBJECTS = %w[
  boot.o
].freeze

LIBRARIES = %w[
  execute_elf
  file
  ipc
  log
  memory
  string
  system
].freeze

OUTPUT = 'boot'.freeze

load '../../servers.rake'
