# frozen_string_literal: true
OBJECTS = %w(
  boot.o
).freeze

LIBRARIES = %w(
  execute_elf
  file
  ipc
  log
  memory
  string
  system
).freeze

OUTPUT = 'boot'.freeze
EXTRA_LDFLAGS_PRE = '-Wl,--defsym=PROCESS_VM_BASE=0x49000000'

load '../../servers.rake'
