/* Automatically generated by autochaos 0.2.1. Not intended to be
   hand edited. */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define PACKAGE_NAME "cluido"
#define PACKAGE_VERSION "0.1.0"

#include <checksum/checksum.h>
#include <console/console.h>
#include <execute_elf/execute_elf.h>
#include <file/file.h>
#include <ipc/ipc.h>
#include <log/log.h>
#include <math/math.h>
#include <memory/memory.h>
#include <ipv4/ipv4.h>
#include <pci/pci.h>
#include <random/random.h>
#include <string/string.h>
#include <time/time.h>
#include <unicode/unicode.h>
#include <system/system.h>
#include <video/video.h>

#endif /* !__CONFIG_H__ */
