# frozen_string_literal: true
OBJECTS = %w(
  cluido.o
  command.o
  init.o
  nibbles.o
).freeze

LIBRARIES = %w(
  console
  execute_elf
  file
  ipc
  ipv4
  memory
  pci
  random
  string
  system
  time
  unicode
).freeze

OUTPUT = 'cluido'.freeze

load '../programs.rake'
