# frozen_string_literal: true

OBJECTS = %w[
  cluido.o
  command.o
  init.o
].freeze

LIBRARIES = %w[
  console
  execute_elf
  file
  ipc
  ipv4
  memory
  pci
  random
  string
  system
  time
  unicode
].freeze

OUTPUT = 'cluido'.freeze
EXTRA_LDFLAGS_PRE = '-Wl,--defsym=PROCESS_VM_BASE=0x58000000'.freeze

load '../programs.rake'
