# frozen_string_literal: true

Rake.application.options.rakelib = [pwd + '/../rakelib'] if Rake.application.options.rakelib.first == 'rakelib'

SUBFOLDERS = %w[
  cluido
  modplay
  tetris
].freeze

# Not yet converted to rake:
#
#   sampleplay
#   serialtest
#   streamplay
#   tetris

task default: SUBFOLDERS do |t|
  t.prerequisites.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND}"
  end
end

task :clean do
  SUBFOLDERS.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} clean"
  end
end

task install: :default do
  # The volume is always recreated on 'rake install', so the folder structure must be created from scratch.
  sh 'mmd u:/config'
  sh 'mmd u:/config/servers'
  sh 'mmd u:/config/servers/boot'
  sh 'mcopy -o startup u:/config/servers/boot'

  sh 'mmd u:/programs'

  SUBFOLDERS.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} install"
  end
end
