Rake.application.options.rakelib = [pwd + '/../rakelib'] if Rake.application.options.rakelib.first == 'rakelib'

SUBFOLDERS = %w(
  cluido
)

task :default => SUBFOLDERS do |t|
  t.prerequisites.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND}"
  end
end

task :clean do
  SUBFOLDERS.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} clean"
  end
end

task :install => :default do
  # Disabled for now, since the code that generates the folder structure isn't here yet.
  #sh 'mcopy -o startup u:/config/servers/boot'

  SUBFOLDERS.each do |folder|
    sh "cd #{folder} && #{RAKE_COMMAND} install"
  end
end
