OBJECTS = %w(
  initial_ramdisk.o
  ramdisk.o
)

LIBRARIES = %w(
  ipc
  log
  memory
  string
  system
)

OUTPUT = 'initial_ramdisk'

file 'initial_ramdisk.o' => ['initial_ramdisk.c', 'ramdisk-auto.h']

file 'ramdisk-auto.h' => ['ramdisk.rb', 'ramdisk.image'] do |t|
  print((t.name + ' ').cyan)

  sh './ramdisk.rb ramdisk.image > ramdisk-auto.h'
end

load '../../servers.rake'
